### ISSUE TITLE
Some questions about Shannon entropy specificity.

### ISSUE THREAD

**Issue by User-yx** [apcamargo/tspex#16]
Hi, thank you very much for providing such a convenient tool. I have a few questions to ask:

1.In the calculation of Shannon entropy specificity (HS), 'H' represents the value of entropy. What do 'HS' and 'HS'' mean? Suppose I have a matrix where rows represent genes and columns represent tissues, and the values inside represent the expression levels of genes in tissues. In the end, should I use the value of 'HS'' to filter genes that show tissue-specific gene? How should I choose the threshold? Do I need to calculate significance?
2.Between Shannon entropy specificity (HS) and Tau, which method is more suitable for computing tissue-specific gene or regulatory elements?

**Comment by apcamargo** [comment]
Hi @User-yx,

- H is high when specificity is low, while HS is proportional to specificity. HS' is just a transformed HS so that the values fall within the [0, 1] interval. You can check the formulas for each one of these metrics [here](https://apcamargo.github.io/tspex/metrics/#shannon-entropy-specificity-hs).
- I don't think there's one definitive answer for this, as different metrics will have different distributions. You can read a benchmark comparing Tau, HS, and some other metrics [here](https://academic.oup.com/bib/article/18/2/205/2562739). I recommend plotting the values you obtain for both metrics for a couple of genes of interest and picking the one that allows you to answer your biological questions better (which is something that can be very tricky to quantify).

**Comment by User-yx** [comment]
Thank you very much for your response!
