### ISSUE TITLE
ValueError: Length of passed values is 1, index implies 5.

### ISSUE THREAD

**Issue by pedronavaja** [apcamargo/tspex#8]
Hello, 

I can't seem to get SPM, Roku or Shannon Specificity to work with your package. The same error is returned - `ValueError: Length of passed values is 1, index implies n` Where `n` is the number of columns in the passed dataframe. I can't quite tell why this is happening, though. Any thoughts? I was quite happy to see that you had built this package, but I have not gotten it to run successfully so far...

**Comment by apcamargo** [comment]
Hi @pedronavaja!

This issue was probably caused by some change in the newer pandas version. I just fixed the bug and and now uploading the new version.

Thank you for letting me know of this bug! It took some time for me too see the issue because GitHub didn't send me any email. I now have activated notifications for this repo.
